---
- name: Deploy Kubernetes Blog Website
  hosts: all
  become: yes

  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Copy index.html to Nginx directory
      ansible.builtin.copy:
        src: /root/ansible-1/index.html
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Start and enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
