---
- name: Install and start Nginx
  hosts: all
  become: yes

  tasks:
    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present
        update_cache: yes

    - name: Start and enable Nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes