- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Start Nginx service
  service:
    name: nginx
    state: started
    enabled: true

- name: Ensure Nginx is running
  command: systemctl status nginx
  register: nginx_status

- name: Print Nginx status
  ansible.builtin.debug:
  msg: "Nginx status: {{ nginx_status }}"

- name: print variables
  ansible.builtin.debug:
    msg:"nginx is insatlled by {{ devops_engineer}} and {{ project_name}} with {{ user_id}}"